config_vars: config_vars.yaml
components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        dynamic-config:
            updates-enabled: true
            fs-cache-path: $config-cache
            fs-task-processor: fs-task-processor

        dynamic-config-client:
            config-url: $config-server-url
            http-retries: 5
            http-timeout: 20s
            service-name: chat

        dynamic-config-client-updater:
            config-settings: false
            first-update-fail-ok: true
            full-update-interval: 1m
            update-interval: 5s

        default-secdist-provider:
            config: secure_data.json

        testsuite-support: {}

        congestion-control:
            load-enabled: false

        http-client:
        http-client-core:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            load-enabled: true
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        ydb:
            load-enabled: true
            operation-settings:
                cancel-after: 1000ms
                client-timeout: 1100ms
                operation-timeout: 1000ms
                retries: 3
            databases:
                chat_db:
                    database: chat_db
                    max_pool_size: 10
                    min_pool_size: 5

        coordination-repository:
            load-enabled: true
            dbname: chat_db

        coordination-gateway:
            load-enabled: true
            dbname: chat_db
            coordination-node: chat-coordination
            partition-map-semaphore: partition-map-lock
            discovery-semaphore: discovery-lock
            initial-setup: true

        hub-gateway:
            load-enabled: true

        load-factor-predictor:
            load-enabled: true
            type: heuristic

        leader-dist-lock:
            load-enabled: true
            database-settings:
                dbname: chat_db
                coordination-node: chat-coordination
            semaphore-name: partition-map-lock

        leader-service:
            load-enabled: true

        admin-service:
            load-enabled: true

        handler-ping:
            load-enabled: true
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-context:
            load-enabled: true
            path: /admin/context
            method: GET
            task_processor: main-task-processor
            
        handler-get-partition-map:
            load-enabled: true
            path: /admin/partition_map
            method: GET
            task_processor: main-task-processor
            
        handler-get-partition:
            load-enabled: true
            path: /admin/partition
            method: GET
            task_processor: main-task-processor

        handler-get-hub-reports:
            load-enabled: true
            path: /admin/hub_reports
            method: GET
            task_processor: main-task-processor
